// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIOY85z-FjGaO6wyCTrjyyTqQAWJawkBc',
    appId: '1:800901874318:web:efca8d39a9d76bdf527fdf',
    messagingSenderId: '800901874318',
    projectId: 'nexo-app-511a9',
    authDomain: 'nexo-app-511a9.firebaseapp.com',
    storageBucket: 'nexo-app-511a9.firebasestorage.app',
    measurementId: 'G-LEB0YVG1VM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPBV_AWnycaDH-sn4GxXHhg9I1vS3aVnc',
    appId: '1:800901874318:android:08dc4b4c7dee526c527fdf',
    messagingSenderId: '800901874318',
    projectId: 'nexo-app-511a9',
    storageBucket: 'nexo-app-511a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaVgus2vCMyIIY8YbyqWhv6PMOUe_Yr7M',
    appId: '1:800901874318:ios:eca5522dafbdd96c527fdf',
    messagingSenderId: '800901874318',
    projectId: 'nexo-app-511a9',
    storageBucket: 'nexo-app-511a9.firebasestorage.app',
    iosClientId: '800901874318-bvrnli3im5bnnsbl54si14j5ob0m4tvs.apps.googleusercontent.com',
    iosBundleId: 'com.example.nexoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaVgus2vCMyIIY8YbyqWhv6PMOUe_Yr7M',
    appId: '1:800901874318:ios:eca5522dafbdd96c527fdf',
    messagingSenderId: '800901874318',
    projectId: 'nexo-app-511a9',
    storageBucket: 'nexo-app-511a9.firebasestorage.app',
    iosClientId: '800901874318-bvrnli3im5bnnsbl54si14j5ob0m4tvs.apps.googleusercontent.com',
    iosBundleId: 'com.example.nexoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIOY85z-FjGaO6wyCTrjyyTqQAWJawkBc',
    appId: '1:800901874318:web:a9e9df1d339f68c7527fdf',
    messagingSenderId: '800901874318',
    projectId: 'nexo-app-511a9',
    authDomain: 'nexo-app-511a9.firebaseapp.com',
    storageBucket: 'nexo-app-511a9.firebasestorage.app',
    measurementId: 'G-5QC1ZV25BY',
  );
}
